# a = open("file a.txt","x")
# b = open("file a.txt", "r")
# c = open("file a.txt", "w")
# c.write("nem line in the file")
# c.close()
# e = open("file a.txt","a")
# e.write("\n appended line in teh file")
# e.close()
# flie = open("mynote.txt","x")
# file = open("mynote.txt","r")
# print(file.read())
# file = open("mynote.txt", "w")
# text1 = "python is programing languange\n"
# file.write("python is easy to learn")
# file.close()
# file = open("mynote.txt", "w")
# text1 = ("python is programming languange\n")
# file.write(text1)
# file.write("python is easy to learn")
# file.close()
# file2 = open("newnote.txt", "w")
# file2.write("my goals\n")
# file2.write("==========")
# file2.close()
# file2 = open("mynote.txt", "w")
# file2.write("okay")
# file2.close()
file = open("mybio.txt","w")
file.write('nama lengkap: zaahid azka lobma\n')
file.write("nama panggilan: zaahid\n")
file.write("umur: 13\n")
baca_file = open("mybio.txt","r")
isi_file = baca_file.read()
baca_file.close()
print(isi_file)